openapi: 3.0.0
info:
  title: API CRM
  description: API CRM
  version: 0.1.0
servers:
  - url: https://otlkm.app.n8n.cloud/webhook


schemes:
- "https"
paths:

  /client:
    post:
      summary: Creates a client.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                shipping_address:
                  type: object
                  properties:
                    address:
                      type: string
                    postal_code:
                      type: string
      responses:
        '200':
          description: user id
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
  
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
